#	from @(#)Makefile.inc	8.1 (Berkeley) 6/4/93
# $FreeBSD$

PACKAGE=lib${LIB}
LIB=	regex

CFLAGS+=	-DLIBREGEX_BUILD
SYMBOL_MAPS=	${SYM_MAPS}

.include "${SRCTOP}/lib/libc/regex/Makefile.inc"
.include <bsd.lib.mk>
