# $FReeBSD$

PACKAGE=	tests
TESTSRC=	${SRCTOP}/contrib/netbsd-tests/lib/libc/regex

.PATH:		${SRCTOP}/tests

.include "${SRCTOP}/lib/libc/tests/regex/Makefile.inc"
.include <netbsd-tests.test.mk>
.include <bsd.test.mk>
