# Makefile

PROG=	bootpef
MAN=	bootpef.8
SRCS=	bootpef.c dovend.c readfile.c hash.c dumptab.c lookup.c \
	hwaddr.c report.c tzone.c rtmsg.c
.PATH:	${COMMONSRC}

BINDIR=	/usr/sbin

.include <bsd.prog.mk>
