.\" Copyright (c) 2019 Justin Hibbits
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" $FreeBSD$
.\"
.Dd August 9, 2019
.Dt FDWALK 3
.Os
.Sh NAME
.Nm fdwalk
.Nd iterate over open file descriptors
.Sh LIBRARY
.Lb libc
.Sh SYNOPSIS
.In stdlib.h
.Ft int
.Fn fdwalk "int (*cb)(void *, int)" "void *cbd"
.Sh DESCRIPTION
The
.Nm
function executes a callback for each file descriptor open at the time of its
invocation.
The
.Nm
function passes the
.Ar cbd
argument into the callback, along with each file descriptor.
If
.Ar cbd
returns non-zero, iteration is terminated.
It is async-signal-safe.
.Sh RETURN VALUES
The
.Nm
function always returns 0.
.Sh SEE ALSO
.Xr closefrom 2 ,
.Xr kinfo_getfile 3
.Sh HISTORY
The
.Nm
function first appeared in SunOS.
.Sh BUGS
It only takes a snapshot, so any file descriptors created or removed
after the snapshot is taken, either in another thread or in the callback
function, are not handled.
